// Alex's model transparency — visible AI disclosure on every AI page
export function AIDisclosureBanner() {
  return (
    <div className="bg-teal-50 border border-teal-200 rounded-lg px-4 py-3 flex items-start gap-3 text-sm">
      <span className="text-teal-600 text-lg flex-shrink-0">🤖</span>
      <div>
        <span className="font-semibold text-teal-800">AI Disclosure: </span>
        <span className="text-teal-700">
          This analysis is generated by <strong>GPT-4o (OpenAI)</strong> and is intended as general wellness guidance only — not medical advice. 
          Results may not apply to all users. Always consult a licensed healthcare provider.
        </span>
      </div>
    </div>
  )
}

export function HumanOversightBanner() {
  return (
    <div className="bg-amber-50 border border-amber-200 rounded-lg px-4 py-3 flex items-start gap-3 text-sm">
      <span className="text-amber-600 text-lg flex-shrink-0">⚕️</span>
      <p className="text-amber-800">
        <strong>Human Oversight Required: </strong>
        Care360 AI is a triage and navigation tool — not a replacement for a licensed healthcare provider. 
        A doctor should always make final medical decisions.
      </p>
    </div>
  )
}
